-- MySQL Script generated by MySQL Workbench
-- Sat Jun 20 20:28:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema findjobsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema findjobsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `findjobsdb` DEFAULT CHARACTER SET utf8 ;
USE `findjobsdb` ;

-- -----------------------------------------------------
-- Table `findjobsdb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findjobsdb`.`usuarios` (
  `cpf` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `dataNascimento` VARCHAR(45) NOT NULL,
  `telefone` INT(60) NOT NULL,
  `tempoExperiencia` VARCHAR(45) NOT NULL,
  `profissao` VARCHAR(45) NOT NULL,
  `avatarUrl` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findjobsdb`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findjobsdb`.`projetos` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `cpfFreela` INT(100) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `imgUrl` VARCHAR(45) NOT NULL,
  `salario` DOUBLE NOT NULL,
  `dataEntrega` DATE NOT NULL,
  `cliente_cpf` INT NOT NULL,
  PRIMARY KEY (`idProjeto`, `cliente_cpf`),
  INDEX `fk_projetos_usuario_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_projetos_usuario`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `findjobsdb`.`usuarios` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findjobsdb`.`reclamacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findjobsdb`.`reclamacoes` (
  `idReclamacao` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(200) NOT NULL,
  `urgencia` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `estadoReclamacao` BINARY(1) NOT NULL,
  PRIMARY KEY (`idReclamacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findjobsdb`.`usuarios_reclamacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findjobsdb`.`usuarios_reclamacoes` (
  `usuario_cpf` INT NOT NULL,
  `reclamacao_idReclamacao` INT NOT NULL,
  PRIMARY KEY (`usuario_cpf`, `reclamacao_idReclamacao`),
  INDEX `fk_usuario_has_reclamacao_reclamacao1_idx` (`reclamacao_idReclamacao` ASC),
  INDEX `fk_usuario_has_reclamacao_usuario1_idx` (`usuario_cpf` ASC),
  CONSTRAINT `fk_usuario_has_reclamacao_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `findjobsdb`.`usuarios` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_reclamacao_reclamacao1`
    FOREIGN KEY (`reclamacao_idReclamacao`)
    REFERENCES `findjobsdb`.`reclamacoes` (`idReclamacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
