-- MySQL Script generated by MySQL Workbench
-- Fri Jun 26 13:37:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema findjobs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema findjobs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `findjobs` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `findjobs` ;

-- -----------------------------------------------------
-- Table `findjobs`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findjobs`.`usuarios` (
  `cpf` BIGINT(200) NOT NULL,
  `nome` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `senha` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `datanascimento` DATE NOT NULL,
  `telefone` BIGINT(200) NOT NULL,
  `experiencia` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `avatarurl` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `profissao` VARCHAR(200) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findjobs`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findjobs`.`projetos` (
  `idprojetos` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `descricao` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `salario` DECIMAL NOT NULL,
  `cpffreela` BIGINT(200) NULL,
  `imgurl` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `linguagem` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `dataentrega` DATE NOT NULL,
  `cliente_cpf` BIGINT(200) NOT NULL,
  PRIMARY KEY (`idprojetos`),
  INDEX `fk_projetos_usuarios_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_projetos_usuarios`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `findjobs`.`usuarios` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findjobs`.`reclamacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findjobs`.`reclamacoes` (
  `idreclamacoes` INT NOT NULL AUTO_INCREMENT,
  `opniao` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `usuario_cpf` BIGINT(200) NOT NULL,
  `estrelas` INT(10) NOT NULL,
  PRIMARY KEY (`idreclamacoes`),
  INDEX `fk_reclamacoes_usuarios1_idx` (`usuario_cpf` ASC) ,
  CONSTRAINT `fk_reclamacoes_usuarios1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `findjobs`.`usuarios` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
